set-option -g default-shell /usr/bin/bash
set -g default-terminal "screen-256color"

# Address vim mode switching delay
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

set -g display-time 4000
set -g status-interval 5
set -g focus-events on

# Emacs key bindings in tmux command prompt (prefix + :)
set -g status-keys emacs

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

unbind C-b
set -g prefix C-a

bind C-a send-prefix
bind a last-window

bind C-p previous-window
bind C-n next-window

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set-option -g -q mouse on

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

# Use vim keybindings in copy mode
setw -g mode-keys vi

unbind-key -T copy-mode-vi v

bind-key -T copy-mode-vi v \
  send-keys -X begin-selection

bind-key -T copy-mode-vi 'C-v' \
  send-keys -X rectangle-toggle

bind-key -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "wl-copy"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "wl-copy"

bind c new-window -c '#{pane_current_path}'

bind '\' split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

bind b break-pane -d

set-option -g status-justify left
set-option -g status-left '#[bg=colour72] #[bg=colour237] #[bg=colour236] #[bg=colour235]#[fg=colour185] #S #[bg=colour236] '
set-option -g status-left-length 16
set-option -g status-bg colour237
set-option -g status-right '#[bg=colour236] #[bg=colour235]#[fg=colour185] #[bg=colour236]#[fg=colour3] #[bg=colour237] #[bg=colour72] #[]'

set-option -g pane-active-border-style fg=colour246
set-option -g pane-border-style fg=colour238

set-window-option -g window-status-format '#[bg=colour238]#[fg=colour107] #I #[bg=colour239]#[fg=colour110] #[bg=colour240]#W#[bg=colour239]#[fg=colour195]#F#[bg=colour238] '
set-window-option -g window-status-current-format '#[bg=colour236]#[fg=colour215] #I #[bg=colour235]#[fg=colour167] #[bg=colour234]#W#[bg=colour235]#[fg=colour195]#F#[bg=colour236] '

run '~/.config/tmux/plugins/tpm/tpm'
